<?php
declare(strict_types=1);

/**
 * Isolated integration-test bootstrap (Task 2 harness).
 *
 * Contract (enforced fail-closed):
 *  - Every test PROCESS gets its own unique temp root under the OS temp dir
 *    (never under the repository: no storage/sqlite, no repo session dirs).
 *  - DB_DRIVER=sqlite is forced, so the production bootstrap builds its
 *    schema against a fresh (bootstrap-recreated) sqlite directory instead
 *    of the live MySQL or the pre-existing repo dev database.
 *  - The pre-existing repo storage/sqlite directory is STASHED (renamed
 *    aside) for the whole run and RESTORED by a shutdown-registered
 *    callback, so the harness never reads or writes pre-existing repo
 *    dev data. The directory the unmodified bootstrap recreates during
 *    app boot contains ONLY data generated by this run; teardown removes
 *    it (with an mtime safety check) before restoring the stash.
 *  - Native sessions are pointed at a temp save_path with a unique name/ID.
 *  - A known test-only JWT secret overrides the (placeholder) dev .env value
 *    without ever modifying .env on disk.
 *  - HA/TAC path constants are pointed at nonexistent temp locations, so the
 *    app boots 'standalone' without touching /opt/tgui_data or /opt/tacacsgui.
 *  - If any temp path cannot be created/written, bootstrap THROWS. There is
 *    deliberately no fallback to .env MySQL values.
 *
 * Teardown is registered BEFORE any app construction, so an interrupted run
 * still removes the temp root and restores the stashed repo directory.
 */

use tgui\Tests\Support\EnvSnapshot;
use tgui\Tests\Support\IsolatedEnvironment;

require __DIR__ . '/../vendor/autoload.php';

$repoStorage = dirname(__DIR__) . '/storage/sqlite';
$repoParent = dirname(__DIR__) . '/storage';

// 0a. Crash-safe residue removal: if a previous run's teardown could not
//     remove the run-generated storage dir (9p held the last handle past
//     process exit), a tombstone was left. Remove the residue + tombstone
//     before stashing. The residue is run-generated by construction (the
//     real pre-run data was stashed by that run, so it is inside a stash,
//     not here). Safety: only remove files NEWER than the tombstone — but
//     9p timestamps are coarse, so a file that fails unlink() is treated
//     as held-by-OS (fresh residue) rather than as foreign data.
$tombstones = glob($repoParent . '/.t2-residue-sqlite') ?: [];
foreach ($tombstones as $tb) {
    $tbTime = (int) @filemtime($tb);
    if (is_dir($repoStorage)) {
        $unsafe = false;
        foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($repoStorage, FilesystemIterator::SKIP_DOTS)) as $it) {
            if ($it->isDir()) {
                continue;
            }
            $p = $it->getPathname();
            if ((int) $it->getMTime() < $tbTime && @unlink($p) === false) {
                $unsafe = true; // older than tombstone AND not removable
                break;
            }
        }
        if ($unsafe) {
            throw new RuntimeException('Storage dir contains foreign pre-tombstone files; refusing to remove: ' . $repoStorage);
        }
        IsolatedEnvironment::removeTree($repoStorage);
    }
    @unlink($tb);
}

// 1. Unique per-run temp root under the OS temp dir (fail-closed creation).
//    The OS temp dir is a 9p mount on this Windows host; creation is
//    retried a bounded number of times before giving up.
$runId = bin2hex(random_bytes(4)) . '-' . getmypid();
$runRoot = IsolatedEnvironment::createTempRoot('tgui-phpunit-' . $runId, retries: 5);

// 2. Run-start marker, written BEFORE the stash so that (with 9p's coarse
//    timestamps) every file the run later creates is strictly newer.
@file_put_contents($runRoot . '/.t2-run-start', (string) time());
usleep(1100000);

// 3. Stash recovery: if crashed runs left stashes, restore the one holding
//    the NEWEST content (that is the real pre-run repo data; the rest are
//    run-generated leftovers from failed teardowns) and remove the rest.
//
//    The real pre-run db is a FULLY BUILT schema (hundreds of tables, a
//    non-trivial file size); anything a crashed teardown left behind is a
//    FRESH bootstrap build (a few dozen KB at most). The score therefore
//    weighs file size first, content mtime second.
$stale = glob($repoStorage . '.t2stash-*') ?: [];
if ($stale !== []) {
    if (is_dir($repoStorage)) {
        throw new RuntimeException('Both repo storage dir and stale stashes exist; refusing to decide which holds repo data: ' . implode(' ', $stale));
    }
    $score = static function (string $s): int {
        $m = 0;
        $sz = 0;
        foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($s, FilesystemIterator::SKIP_DOTS)) as $it) {
            if (!$it->isDir()) {
                $m = max($m, (int) $it->getMTime());
                $sz += (int) $it->getSize();
            }
        }
        // Size in KB (0-999999) + newest mtime: full pre-run data (176KB+)
        // always outranks a fresh build (<=40KB) regardless of mtime.
        return min(999999, intdiv($sz, 1024)) * 1000000000 + $m;
    };
    usort($stale, static fn (string $a, string $b): int => $score($b) <=> $score($a));
    @rename($stale[0], $repoStorage);
    array_splice($stale, 0, 1);
    foreach ($stale as $s) {
        IsolatedEnvironment::removeTree($s);
    }
}

// 4. Stash the pre-run repo storage/sqlite so the suite can never read or
//    write pre-existing dev data. Record its content mtime (newest file)
//    for the teardown safety check.
$repoStash = $repoStorage . '.t2stash-' . getmypid();
if (is_dir($repoStorage)) {
    if (!@rename($repoStorage, $repoStash)) {
        throw new RuntimeException('Cannot isolate repo storage/sqlite (rename to ' . $repoStash . ' failed); refusing to run the suite against repo dev data.');
    }
    $contentMtime = 0;
    foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($repoStash, FilesystemIterator::SKIP_DOTS)) as $it) {
        if (!$it->isDir()) {
            $contentMtime = max($contentMtime, (int) $it->getMTime());
        }
    }
    @file_put_contents($runRoot . '/.t2-stash-mtime', (string) $contentMtime);
} else {
    @file_put_contents($runRoot . '/.t2-stash-mtime', '0');
}

// 5. Register teardown (idempotent, never throws) so an interrupted run
//    still cleans up: removes the run-generated repo storage dir, restores
//    the stash, removes the temp root.
//
//    CONTENT SAFETY (not mtime): the pre-run repo db is a fully populated
//    schema (hundreds of CREATE TABLEs). Anything the bootstrap recreates
//    during this run is a FRESH build from scratch and cannot be
//    byte-identical to it. Teardown verifies by CONTENT: if the db file
//    still hashes like the stashed pre-run file, it is NOT run-generated
//    and is left in place for inspection. Robust against 9p timestamp
//    coarseness and rename/restore races.
$preDbHash = static function (string $dir): ?string {
    $f = $dir . '/tgui.sqlite';
    return is_file($f) ? hash_file('sha256', $f) : null;
};
$stashDbHash = is_dir($repoStash) ? $preDbHash($repoStash) : null;
$teardown = static function () use ($runRoot, $repoStorage, $repoStash, $preDbHash, $stashDbHash): void {
    // 5a. Remove the repo storage dir the unmodified bootstrap recreated
    //     during app boot — unless its content is byte-identical to the
    //     stashed pre-run db (that would be real repo data, never touch it).
    if (is_dir($repoStorage)) {
        $currentHash = $preDbHash($repoStorage);
        if ($currentHash !== null && $stashDbHash !== null && $currentHash === $stashDbHash) {
            error_log('t2-bootstrap: repo storage dir content matches pre-run stash (not run-generated); left in place: ' . $repoStorage);
        } else {
            IsolatedEnvironment::removeTree($repoStorage);
        }
    }
    // 5b. Restore the stashed pre-run repo storage dir.
    if (is_dir($repoStash)) {
        if (is_dir($repoStorage)) {
            error_log('t2-bootstrap: repo storage dir present after cleanup; leaving BOTH: ' . $repoStorage . ' and ' . $repoStash);
        } else {
            @rename($repoStash, $repoStorage);
        }
    }
    // 5c. Remove the isolated temp root (retry: 9p unlink can lag).
    IsolatedEnvironment::removeTree($runRoot);
    for ($i = 0; $i < 10 && is_dir($runRoot); $i++) {
        usleep(100000);
        IsolatedEnvironment::removeTree($runRoot);
    }
    if (is_dir($runRoot)) {
        error_log('t2-bootstrap: temp root survived cleanup; left for inspection: ' . $runRoot);
    }
    // 5d. If the run-generated repo storage dir still exists (9p can hold
    //     the last open handle past process exit), leave a tombstone marker
    //     next to it. The NEXT bootstrap run (step 0a) detects the tombstone,
    //     verifies the residue is run-generated, and removes it before
    //     stashing. This keeps every cleanup idempotent and crash-safe
    //     without any cross-process locking.
    if (is_dir($repoStorage) && !is_dir($repoStash)) {
        $tb = dirname($repoStorage) . '/.t2-residue-sqlite';
        @file_put_contents($tb, (string) time());
        // Best-effort immediate retry: often the OS releases the handle a
        // moment later, so the next run (or even a brief wait) succeeds.
        for ($i = 0; $i < 20 && is_dir($repoStorage); $i++) {
            usleep(100000);
            IsolatedEnvironment::removeTree($repoStorage);
        }
        if (!is_dir($repoStorage)) {
            @unlink($tb); // residue went away; no tombstone needed
        }
    }
};
register_shutdown_function($teardown);

// 6. Force deterministic env values. EnvSnapshot captures the pre-test state
//    of the globals the suite may touch so tests (and tasks 4-8) can restore
//    exact values instead of leaking between cases.
$snapshot = new EnvSnapshot([
    'DB_DRIVER',
    'TGUI_TEST_SQLITE_DEFAULT',
    'TGUI_TEST_SQLITE_LOG',
    'HA_SETTINGS_PATH',
    'HA_MASTER_PATH',
    'HA_SLAVES_PATH',
    'TAC_ROOT_PATH',
    'JWT_SECRET',
    'JWT_ALGORITHM',
]);
$snapshot->apply([
    // Force the dev-only SQLite branch of bootstrap/app.php.
    'DB_DRIVER' => 'sqlite',
    // Two temp database files (default + logging) as required by the
    // current schema code (bootstrap registers two sqlite connections).
    'TGUI_TEST_SQLITE_DEFAULT' => $runRoot . '/tgui-test.sqlite',
    'TGUI_TEST_SQLITE_LOG' => $runRoot . '/tgui-test-log.sqlite',
    // Point HA constants at nonexistent temp paths -> app boots 'standalone'
    // without reading /opt/tgui_data.
    'HA_SETTINGS_PATH' => $runRoot . '/ha/ha-settings.yaml',
    'HA_MASTER_PATH' => $runRoot . '/ha/ha-master.yaml',
    'HA_SLAVES_PATH' => $runRoot . '/ha/ha-slaves.yaml',
    // Keep TAC+ path constants away from the live install root.
    'TAC_ROOT_PATH' => $runRoot . '/tacacsgui',
    // Known test-only JWT secret (NOT a placeholder, NOT the dev value).
    // Overridden in-process; web/api/.env on disk is never modified.
    'JWT_SECRET' => IsolatedEnvironment::TEST_JWT_SECRET,
    'JWT_ALGORITHM' => 'HS256',
]);

// 7. Pre-create the two isolated SQLite files as REAL empty databases
//    (a zero-length file makes PDO sqlite fail with "file is not a
//    database"). Fail closed on any creation/writability problem.
//
//    PLATFORM NOTE: the pdo_sqlite extension must be present in the PHP
//    that runs the suite. It is present on the Windows CLI (C:\php) and on
//    the WSL Ubuntu-24.04 runtime used by the production stack; a minimal
//    PHP build without it fails here with a controlled "could not find
//    driver" — the harness refuses to run rather than fall back anywhere.
if (!in_array('sqlite', PDO::getAvailableDrivers(), true)) {
    throw new RuntimeException('pdo_sqlite is not available in this PHP build; the isolated harness cannot run (no MySQL fallback).');
}
foreach (['TGUI_TEST_SQLITE_DEFAULT', 'TGUI_TEST_SQLITE_LOG'] as $key) {
    $f = (string) $_ENV[$key];
    $d = dirname($f);
    if (!is_dir($d) && !@mkdir($d, 0700, true)) {
        throw new RuntimeException("Cannot create SQLite directory for {$key} (refusing to fall back to MySQL): " . $d);
    }
    if (!is_file($f) && !@touch($f)) {
        throw new RuntimeException("Cannot create SQLite file for {$key} (refusing to fall back to MySQL): " . $f);
    }
    $pdo = new PDO('sqlite:' . $f);
    $pdo->exec('CREATE TABLE IF NOT EXISTS _harness_init (id INTEGER PRIMARY KEY);');
    $pdo = null;
    if (!is_writable($f)) {
        throw new RuntimeException("SQLite file for {$key} is not writable (refusing to fall back to MySQL): " . $f);
    }
}

// 8. Unique native-session configuration (name/id/save path) in this process.
IsolatedEnvironment::configureTestSession($runRoot);

// 9. Expose the run context to tests.
IsolatedEnvironment::setRunContext($runRoot, $snapshot);
