#!/bin/bash
# func_web.sh - web tier: self-signed cert, Angie vhosts, PHP-FPM pool/ini, activate.
# Sourced by install.sh after map.sh (and after func_app.sh has placed the code).
# Defines: web_ssl, web_angie, web_fpm, web_activate.
# Idempotent.

web_ssl() {
    # Ensure the SSL data directory exists.
    mkdir -p "${TGUI_DATA_SSL}"

    if [ "${WEBSERVER_SELFSIGNED_CERT}" = "1" ]; then
        # Generate a self-signed cert/key if absent.
        if [ ! -f "${TGUI_DATA_SSL}/${WEBSERVER_NAME}.cer" ] || [ ! -f "${TGUI_DATA_SSL}/${WEBSERVER_NAME}.key" ]; then
            openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
              -keyout "${TGUI_DATA_SSL}/${WEBSERVER_NAME}.key" \
              -out "${TGUI_DATA_SSL}/${WEBSERVER_NAME}.cer" \
              -subj "/CN=${WEBSERVER_NAME}"
        fi

        # The vhost template uses the fixed filenames tacacsgui.local.cer / .key;
        # map the generated cert onto those fixed names. The operator can later
        # replace these with a real CA-issued cert.
        #
        # GUARD: when WEBSERVER_NAME is already "tacacsgui.local" (the default),
        # the generated filenames ARE the fixed names, so a naive `cp` would copy
        # a file onto itself and fail with "are the same file". Skip the copy in
        # that case (and any other src==dst situation) by comparing inode+device.
        local src_cer="${TGUI_DATA_SSL}/${WEBSERVER_NAME}.cer"
        local src_key="${TGUI_DATA_SSL}/${WEBSERVER_NAME}.key"
        local dst_cer="${TGUI_DATA_SSL}/tacacsgui.local.cer"
        local dst_key="${TGUI_DATA_SSL}/tacacsgui.local.key"
        if [ ! -e "$dst_cer" ] || [ "$(stat -c '%d:%i' "$src_cer")" != "$(stat -c '%d:%i' "$dst_cer")" ]; then
            cp -f "$src_cer" "$dst_cer"
        fi
        if [ ! -e "$dst_key" ] || [ "$(stat -c '%d:%i' "$src_key")" != "$(stat -c '%d:%i' "$dst_key")" ]; then
            cp -f "$src_key" "$dst_key"
        fi

        chmod 600 "${TGUI_DATA_SSL}"/*.key 2>/dev/null || true

        echo "SSL ready (self-signed) for ${WEBSERVER_NAME}"
    else
        echo "NOTE: self-signed cert disabled; place a real cert/key at:"
        echo "  ${TGUI_DATA_SSL}/tacacsgui.local.cer"
        echo "  ${TGUI_DATA_SSL}/tacacsgui.local.key"
        echo "before activating the web server."
        return 0
    fi
}

web_angie() {
    # Ensure the Angie sites directory exists.
    mkdir -p "${ANGIE_SITES_DIR}"

    # Disable the stock Angie "Welcome to Angie" default vhost. It ships with
    # `listen 80 default_server` and would shadow our app vhost (especially
    # when the client connects by IP / with a non-matching Host header). We
    # rename it out of the include dir (idempotent; safe if already gone).
    if [ -f "${ANGIE_SITES_DIR}/default.conf" ]; then
        mv -f "${ANGIE_SITES_DIR}/default.conf" "${ANGIE_SITES_DIR}/default.conf.disabled"
        echo "Disabled stock Angie default vhost (default.conf -> .disabled)"
    fi

    # Always install the HTTP (:80) vhost, overwriting idempotently.
    install -m 644 "${CONF_DIR}/angie/tacacsgui.conf" "${ANGIE_SITES_DIR}/tacacsgui.conf"
    sed -i "s/server_name .*;/server_name ${WEBSERVER_NAME};/" \
        "${ANGIE_SITES_DIR}/tacacsgui.conf"

    # Only install the SSL vhost if a cert is present (self-signed generated by web_ssl,
    # or a real cert the operator placed). Otherwise angie -t will fail on missing cert.
    if [ -f "${TGUI_DATA_SSL}/tacacsgui.local.cer" ] && [ -f "${TGUI_DATA_SSL}/tacacsgui.local.key" ]; then
        install -m 644 "${CONF_DIR}/angie/tacacsgui-ssl.conf" "${ANGIE_SITES_DIR}/tacacsgui-ssl.conf"
        sed -i "s/server_name .*;/server_name ${WEBSERVER_NAME};/" "${ANGIE_SITES_DIR}/tacacsgui-ssl.conf"
        echo "SSL vhost installed (cert present)"
    else
        echo "NOTE: no cert at ${TGUI_DATA_SSL}/tacacsgui.local.{cer,key}; skipping SSL vhost."
        echo "      Place a cert and re-run the installer (or the web step) to enable HTTPS."
    fi

    echo "Angie vhosts installed for ${WEBSERVER_NAME}"
}

web_fpm() {
    # The FPM ini references /var/log/tacacsgui for error_log; make sure the
    # directory exists BEFORE we restart FPM, else workers started now can't
    # open the log. (finalize_dirs also creates it later, but FPM needs it first.)
    mkdir -p "${TGUI_LOG_DIR}"

    # Install the PHP-FPM pool and ini overrides (idempotent overwrite).
    install -m 644 "${CONF_DIR}/php/tgui-fpm-pool.conf" "${FPM_POOL_DEST}"
    install -m 644 "${CONF_DIR}/php/80-tacacsgui.ini" "${FPM_INI_DEST}"

    # Restart PHP-FPM so it picks up the new pool/ini.
    systemctl restart "php${PHP_VERSION}-fpm"

    echo "PHP-FPM pool + ini installed"
}

web_activate() {
    # Validate the Angie config before touching the service.
    if ! angie -t; then
        echo "ERROR: angie config test failed; not reloading a broken config."
        return 1
    fi

    # Enable + start the web server. Note: the Angie package's service is named
    # `angie`; if your distro ships it as `nginx`, substitute that name.
    systemctl enable --now angie

    # Reload to pick up the new vhosts (fall back to restart if reload unsupported).
    systemctl reload angie || systemctl restart angie

    echo "Angie activated; app reachable at https://${WEBSERVER_NAME}"
}
